services:
  backend:
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pcbot_backend
    restart: unless-stopped
    environment:
      - DATABASE_PATH=/app/data/database.db
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL:-}
      - OLLAMA_HOST=${OLLAMA_HOST:-http://host.docker.internal:8080}
      - LLAMA_HOST=${LLAMA_HOST:-http://host.docker.internal:8080}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "127.0.0.1:8000:8000"
    dns:
      - 8.8.8.8
    volumes:
      - pcbot_db_data:/app/data  # Volume nommé Docker persistant
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: pcbot_frontend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - BACKEND_API_URL=http://backend:8000
    ports:
      - "9000:9000"
    depends_on:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  pcbot_db_data:
    name: pcbot_db_data
